[package]
name = "mullvad-ipc-client"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>"]
description = "RPC client for Mullvad daemon"
license = "GPL-3.0"

[dependencies]
error-chain = "0.12"
mullvad-types = { path = "../mullvad-types" }
serde = "1.0"
talpid-ipc-ws = { path = "../talpid-ipc-ws" }
talpid-types = { path = "../talpid-types" }
mullvad-paths = { path = "../mullvad-paths" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.5", features = ["accctrl", "aclapi", "securitybaseapi", "winbase", "winerror", "winnt"] }
