[package]
name = "mullvad-daemon"
version = "2018.2.0-beta3"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Mullvad VPN daemon. Runs and controls the VPN tunnels"
license = "GPL-3.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.25"
error-chain = "0.12"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
uuid = { version = "0.6", features = ["v4"] }
lazy_static = "1.0"
rand = "0.5"
tokio-core = "0.1"
tokio-timer = "0.2"
regex = "1.0"

mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-types = { path = "../mullvad-types" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-core = { path = "../talpid-core" }
talpid-ipc-ws = { path = "../talpid-ipc-ws" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
simple-signal = "1.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.0"
windows-service = { git = "https://github.com/mullvad/windows-service-rs.git", rev = "55c5dfb372e6b3f5607a3159c5388d27b6b84ff6" }
winapi = "0.3"

[target.'cfg(windows)'.build-dependencies]
windres = "0.2"
